//---------------------------------------------------------------------------------------------
#define DECLARE_CONNECTIONPTMAP \
BEGIN_CONNECTION_POINT_MAP(CLASS_WRAPPERCTRL)\
    CONNECTION_POINT_ENTRY(DIID_WRAPPEREVENTS)\
END_CONNECTION_POINT_MAP()


//---------------------------------------------------------------------------------------------
#define DECLARE_IDLBMLWRAPPERCTRL_EVENTS_MESSAGE_HANDLERS \
    /* These are given to IDL, not reflected to client, and marked as 'Handled'*/\
    MESSAGE_HANDLER(WM_GETMINMAXINFO, OnEventIdl)\
    MESSAGE_HANDLER(WM_WINDOWPOSCHANGED, OnEventIdl)\
    MESSAGE_HANDLER(WM_ACTIVATE, OnEventIdl)\
    MESSAGE_HANDLER(WM_PALETTECHANGED, OnEventIdl)\
    MESSAGE_HANDLER(WM_QUERYNEWPALETTE, OnEventIdl)\
    MESSAGE_HANDLER(WM_PAINT, OnEventIdl)\
    MESSAGE_HANDLER(WM_COMMAND, OnEventIdl)\
    MESSAGE_HANDLER(WM_ERASEBKGND, OnEventIdl)\
    MESSAGE_HANDLER(WM_SETCURSOR, OnEventIdl)\
    MESSAGE_HANDLER(WM_MOUSELEAVE, OnEventIdl)\
    MESSAGE_HANDLER(WM_NCMOUSEMOVE, OnEventIdl)\
    MESSAGE_HANDLER(WM_DESTROY, OnEventIdl)\
    MESSAGE_HANDLER(WM_CHAR, OnEventIdl)\
    MESSAGE_HANDLER(WM_SIZE, OnEventIdl)\
    MESSAGE_HANDLER(WM_KEYUP, OnEventIdl)\
    MESSAGE_HANDLER(WM_KEYDOWN, OnEventIdl)\
    MESSAGE_HANDLER(WM_MOUSEMOVE, OnEventIdl)\
    MESSAGE_HANDLER(WM_MOUSEWHEEL, OnEventIdl)\
    MESSAGE_HANDLER(WM_LBUTTONDOWN, OnEventIdl)\
    MESSAGE_HANDLER(WM_MBUTTONDOWN, OnEventIdl)\
    MESSAGE_HANDLER(WM_RBUTTONDOWN, OnEventIdl)\
    MESSAGE_HANDLER(WM_MBUTTONUP, OnEventIdl)\
    MESSAGE_HANDLER(WM_RBUTTONUP, OnEventIdl)\
    MESSAGE_HANDLER(WM_LBUTTONUP, OnEventIdl)\
    MESSAGE_HANDLER(WM_LBUTTONDBLCLK, OnEventIdl)\
    MESSAGE_HANDLER(WM_RBUTTONDBLCLK, OnEventIdl)\
    MESSAGE_HANDLER(WM_MBUTTONDBLCLK, OnEventIdl)

